version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: iam-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-sa}
      POSTGRES_PASSWORD: ${DB_PASS:-12345678}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - iam-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-sa} -d ${DB_NAME:-mydb}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  iam-network:
    driver: bridge
